service: alefuentes-api

provider:
  name: aws
  runtime: nodejs20.x

functions:
  buscarAgendas:
    handler: src/agenda/controller/buscarAgendas.handler
    events:
      - http:
          path: agendas
          method: get
  
  marcarAgendamento:
    handler: src/agendamento/controller/marcarAgendamento.handler
    events:
      - http:
          path: agendamento
          method: post

plugins:
  - serverless-offline
